# This file isn't used. The end goal is to have this auto-generate the
# film.generated.tsx file with a code generator

mutation AddFilm($input: AddFilmInput!) {
  addFilm(input: $input) {
    title
    id
  }
}
